import {api, base_url} from "../apiConfig";

export interface Story {
    title: string;
    description: string;
    content: string; 
    published: "1" | "0";
    image_url: File | string;
}

// Fetches a list of story from the API
export const getStory = async (): Promise<Story[]> => {
  const response = await api(`${base_url}story/`);
  if (response.status !== 200) {
    throw new Error('Failed to fetch story');
  }
  return response.data;
};

export const getStoryWithPagination = async (page: number = 1, limit: number = 10): Promise<{
  story: Story[];
  pagination: {
    page: number;
    limit: number;
    totalPages: number;
    totalRecords: number;
  };
}> => {
  const response = await api.get(`${base_url}giftcards/paginated/?page=${page}&limit=${limit}`);
  if (response.status !== 200) {
    throw new Error('Failed to fetch story with pagination');
  }
  const data = await response.data;
  return {
    story: data.story,
    pagination: data.pagination,
  };
}

// Adds a new Story to the API
export const addGiftCard = async (
  Story: Omit<Story, 'id'> // Excludes 'id' since it's generated by the server
): Promise<Story> => {
  const formData = new FormData();

  // Append the image URL if provided
  formData.append('image', Story.image_url);

  // Append other fields to the form data
  Object.entries(Story).forEach(([key, value]) => {
    if (key !== 'image_url' && value !== undefined && value !== null) {
      formData.append(key, value as string | Blob);
    }
  });

  const response = await api.post(`${base_url}giftcards/`, formData);

  if (response.status !== 201) {
    throw new Error('Failed to add Story');
  }

  return response.data;
};

// Updates an existing Story in the API
export const updateAccommodation = async (
  id: number, // ID of the Story to update
  Story: Partial<Story> // Partial object to allow updating specific fields
): Promise<Story> => {
  const formData = new FormData();

  // Append the image URL if provided]
  formData.append('image', Story.image_url as File);

  // Append other fields to the form data
  Object.entries(Story).forEach(([key, value]) => {
    if (key !== 'image_url' && value !== undefined && value !== null) {
      formData.append(key, value as string | Blob);
    }
  });

  const response = await api.put(`${base_url}giftcards/${id}`, formData);

  if (response.status !== 200) {
    throw new Error('Failed to update Story');
  }

  return response.data;
};

// Deletes an Story from the API
export const deleteAccommodation = async (id: number): Promise<void> => {
  const response = await api.delete(`${base_url}giftcards/${id}`);

  if (response.status !== 200) {
    throw new Error('Failed to delete Story');
  }
};

export const publishAccommodation = async(id: number, published: { published: string }): Promise<Story> => {
    const data = JSON.stringify(published);
    const response = await api.post(`${base_url}giftcards/published/${id}`,data,{
        headers:{
            "Content-Type":"application/json"
        }
    });
    if(response.status !== 200){
        throw new Error("Failed to publish acommodations")
    }

    return response.data;
}